replicaCount: 1
image:
  #repository: "793209430381.dkr.ecr.ap-southeast-1.amazonaws.com/course-service:latest"
  repository: "shashimald/frontend:latest"
  tag: latest
  pullPolicy: Always
service:
  name: frontend-service
  namespace: frontend
  type: ClusterIP
  targetPort: 80
  port: 80
