apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    app: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.service.name}}
  ports:
    - port: {{.Values.service.name}}
      targetPort: {{.Values.service.port}}
