apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.service.name}}
  labels:
    app: {{.Values.service.name}}
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.service.name}}
  template:
    metadata:
      labels:
        app: {{.Values.service.name}}
    spec:
      containers:
        - name: {{.Values.service.name}}
          image: {{.Values.image.repository}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.service.targetPort}}
