{{- if and .Values.auth.enabled (not .Values.secretsManager.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
{{- end }}