apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}