{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.secretsManager.enabled }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- else }}
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{- if not (hasPrefix "eks.amazonaws.com" $key) }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}