replicaCount: 1
image:
  repository: "793209430381.dkr.ecr.ap-southeast-1.amazonaws.com/course-service:latest"
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: course
  namespace: course
  type: ClusterIP
  port: 80
