replicaCount: 1

image:
  repository: shashimald/course-service
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3002

# MongoDB connection details
mongodb:
  host: "sms-mongodb"
  port: 27017

env:
  MONGODB_URI: "mongodb:/sms-mongodb:27017/course-db"
  PORT: "3002"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
