apiVersion: v2
name: sms-app
description: SMS Application Umbrella Chart
type: application
version: 0.1.0
appVersion: "v1.0.0"

dependencies:
  - name: mongodb
    version: "0.1.0"
    repository: "file://../mongodb"
    condition: mongodb.enabled
  - name: course-service
    version: "0.1.0"
    repository: "file://../course-service"
    condition: course-service.enabled
  - name: student-service
    version: "0.1.0"
    repository: "file://../student-service"
    condition: student-service.enabled
  - name: auth-service
    version: "0.1.0"
    repository: "file://../auth-service"
    condition: auth-service.enabled
  - name: frontend
    version: "0.1.0"
    repository: "file://../frontend"
    condition: frontend.enabled
