replicaCount: 1

image:
  repository: shashimald/student-service
  tag: "v1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

# MongoDB connection details
mongodb:
  host: "sms-mongodb"
  port: 27017

env:
  MONGODB_URI: "mongodb://sms-mongodb:27017/student-db"
  PORT: "3001"

# Persistent volume for file uploads
persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  mountPath: /app/uploads

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
