version: '3.8'

services:
  student-service:
    build: ./student
    ports:
      - "8082:8082"
    networks:
      - app-network

  course-service:
    build: ./course
    ports:
      - "8081:8081"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
