apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-mongodb-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: my-app-secret
      type: Opaque
      data:
        - objectName: admin_username
          key: username
        - objectName: admin_password
          key: password
  parameters:
    objects: |
      - objectName: my-app-secret
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: admin_username
          - path: password
            objectAlias: admin_password
